language: go


before_script:
 - go get github.com/koyachi/go-term-ansicolor/ansicolor
 - go get github.com/mattn/go-gntp
script:
 - go build

notifications:
  webhooks:
    - http://wireroom.extremedev.org/=/travis-ci/Hall
